#publicly available docker image "python" on docker hub will be pulled
FROM python:3

# Set label
LABEL build_version="NIIP_LAB5_1.0"
LABEL maintainer="Bram_William"

# Expose port
EXPOSE 5000

ENV ADDR=0 \
    MSG=""

COPY /Client/ /source

# -a ${ADDR} -m "${MSG}"
CMD python3 -u /source/client.py -a ${ADDR}
