#publicly available docker image "python" on docker hub will be pulled
FROM python

# Set label
LABEL build_version="NIIP_LAB5_1.0"
LABEL maintainer="Bram_William"

# Expose port
EXPOSE 5000

ENV TEST="test" \ 
    TEST2="test"

COPY Client/ /source

CMD python3 -u /source/main.py ${TEST} ${TEST2}
